[chain]
chain_id = "gaia"
chain_name = "cosmos"
website = "https://cosmos.network/"

[fetcher]
chain_id = "gaia"
tendermint_rpc_endpoint = "http://localhost:26657"
grpc_endpoint = "http://localhost:9090"
rest_api_endpoint = "http://localhost:1317"
start_block = 1
try_resume_from_db = true

[db]
host = "localhost"
port = 5432
user = "cosmoscout"
password = "cosmoscout"
database = "cosmoscout"