[chain]
chain_id = "gaia"
chain_name = "cosmos"
website = "https://cosmos.network/"

[fetcher]
chain_id = "gaia"
tendermint_rpc = "http://localhost:26657/"
cosmos_grpc = "http://localhost:9090/"
start_block = 1
try_resume_from_db = true

[db]
host = "localhost"
port = 5432
user = "cosmoscout"
password = "cosmoscout"
database = "cosmoscout"