[engine]
fetcher_account_enabled = true

[server]
host = "127.0.0.1"
port = 1337

[chain]
chain_id = "gaia"
chain_name = "cosmos"
website = "https://cosmos.network/"

[fetcher]
tendermint_rpc_endpoint = "http://localhost:26657"
grpc_endpoint = "http://localhost:9090"
rest_api_endpoint = "http://localhost:1317"
start_block = 1
try_resume_from_db = true

[db]
host = "localhost"
port = 5432
user = "cosmscan"
password = "cosmscan"
database = "cosmscan"