version: '3.4'

services:
  testchain:
    image: tendermint/gaia:v4.2.0
    restart: always
    user: root
    volumes:
      - ./scripts:/gaia
      - chain-home:/data/chain
    command:
      - /bin/sh
      - -c
      - |
        echo "start run single node."
        /gaia/init_chain.sh
    ports:
      - 26656:26656
      - 26657:26657
      - 1317:1317
      - 9090:9090
      - 9091:9091
  flood:
    image: tendermint/gaia:v4.2.0
    restart: always
    user: root
    volumes:
      - ./scripts:/gaia
      - chain-home:/data/chain
    command:
      - /bin/sh
      - -c
      - |
        sleep 10;
      
        /gaia/flood.sh
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: "cosmscan"
      POSTGRES_PASSWORD: "cosmscan"
  adminer:
    image: adminer
    restart: always
    ports:
      - "8082:8080"
  migrator:
    depends_on:
      - postgres
      - testchain
    build:
      context: ..
    command:
      - /bin/sh
      - -c
      - |
        # wait for postgres to be ready
        while ! nc -z postgres 5432; do sleep 1; done;

        # run migrations
        cd /app/models
        diesel migration run
  engine:
    depends_on:
      - migrator
      - postgres
      - testchain
    build:
      context: ..
    command:
      - /bin/sh
      - -c
      - |
        # wait for postgres to be ready
        while ! nc -z postgres 5432; do sleep 1; done;
        while ! nc -z testchain 1317; do sleep 1; done;

        RUST_LOG=info /app/release/engine --config-file /app/e2e/config.e2e.toml
  server:
    depends_on:
      - migrator
      - postgres
      - testchain
    build:
      context: ..
    command:
      - /bin/sh
      - -c
      - |
        # wait for postgres to be ready
        while ! nc -z postgres 5432; do sleep 1; done;
        while ! nc -z testchain 1317; do sleep 1; done;

        RUST_LOG=info /app/release/server --config-file /app/e2e/config.e2e.toml
volumes:
  chain-home: